### ISSUE TITLE
Rigueur, systématique : recupPerson/recupMovie

### ISSUE THREAD

**Issue by sagarion** [Tpower36/MovieManager#2]
Récupérer se dit "GET" en anglais donc je comprends pourquoi tu l'as évité vu que tu avais déjà une fonction de ce nom.

Dans la mesure ou ta fonction récupère l'information de la personne ou du film cliqué et sinon lance une erreur en cas de problème. Je te propose "SelectPerson" qui demeure en anglais et garde le sens.

**Comment by Tpower36** [comment]
Not an issue..
